# Configure this Discovery Server
eureka:
  client:  
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1 # DO NOT DO THIS IN PRODUCTION
     
server:
  port: 4444   # HTTP (Tomcat) port

security:
  basic:
    enabled: false
    
spring:
  application:
    name: web-service
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
    enabled: true
  messages:
    basename: messages/messages_en
    cache-seconds: 3600
    
webservice:
  instance:
    persistence:
      name: persistence-service
    

